### ISSUE TITLE
No bundle URL present.

### ISSUE THREAD

**Issue by orzhtml** [lyxia/MyRNStartKit#3]
下载后，ios运行报错。
Make sure you're running a packager server or have included a.jsbundle file in your application bundle.

**Comment by lyxia** [comment]
请看这个回答：https://github.com/lyxia/MyRNStartKit/issues/1

**Comment by orzhtml** [comment]
还是一样。可以给个联系方式么。

**Comment by orzhtml** [comment]
已解决，在XCODE中删除 rn 里面的 ip.txt

**Comment by lyxia** [comment]
谢谢 我待会删了它




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：liuyunxia8@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年03月26日 13:03，Carson Chen 写道： 已解决，在XCODE中删除 rn 里面的 ip.txt

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lyxia/MyRNStartKit","title":"lyxia/MyRNStartKit","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lyxia/MyRNStartKit"}},"updates":{"snippets":[{"icon":"PERSON","message":"@orzhtml in #3: 已解决，在XCODE中删除 rn 里面的 ip.txt"}],"action":{"name":"View Issue","url":"https://github.com/lyxia/MyRNStartKit/issues/3#issuecomment-376047114"}}}
